matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      addons:
        chrome: stable
      before_script: "cd front-end && npm install"
      script: "npm test"
      deploy:
        provider: heroku
        api_key:
          secure: 0ea0ac36-e0d9-48f3-a446-c43a4aeac0b8
        app: pachanga
        on:
          repo: Projeto-Integrado-2020/Pachanga/tree/master/front-end
    - language: java
      jdk:
        - openjdk8
      script: "cd back-end && mvn clean install"
      deploy:
        provider: heroku
        api_key:
          secure: 0ea0ac36-e0d9-48f3-a446-c43a4aeac0b8
        app: pachanga
        on:
          repo: Projeto-Integrado-2020/Pachanga/tree/master/back-end

notifications:  
  email:  
    recipients:  
    - andrey-lacerda@hotmail.com
    - luis.antonio@aluno.ifsp.edu.br
    - tiagostaurenghi@gmail.com
    - guiladriero@gmail.com
    - opedrofreitas@gmail.com
    - guga.72@hotmail.com
  on_success: always 
  on_failure: always
