matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      script: "cd front-end && npm test"
    - language: java
      jdk:
        - openjdk8

notifications:  
  email:  
    recipients:  
    - andrey-lacerda@hotmail.com
    - luis.antonio@aluno.ifsp.edu.br
    - tiagostaurenghi@gmail.com
    - guiladriero@gmail.com
    - opedrofreitas@gmail.com
    - guga.72@hotmail.com
    on_success: never 
    on_failure: never