name: CI/CD Heroku Back e Front

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  front:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Angular 8
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: cd front-end && npm install
      - run: cd front-end && npm test
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_FRONT_API_KEY}}
          heroku_app_name: "pachanga" #Must be unique in Heroku
          heroku_email: "andrey-lacerda@hotmail.com"
          appdir: front-end
  back:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [10]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        

      # Runs a single command using the runners shell
      - name: JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: cd back-end && mvn clean install
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_BACK_API_KEY}}
          heroku_app_name: "pachanga-back-end" #Must be unique in Heroku
          heroku_email: "andrey-lacerda@hotmail.com"
          appdir: back-end
